### ISSUE TITLE
Handle error state

### ISSUE THREAD

**Issue by MoustaphaDev** [withastro/cli-kit#16]
Currently cli-kit expects a command to always succeed. For example, when using the spinner, if an operation fails in the `while` function, the `end` message would still be displayed (unless we exit of course but that's not ideal).

For instance [the dependency installation step](https://github.com/withastro/astro/blob/main/packages/create-astro/src/actions/dependencies.ts#L29) in `create-astro` could fail but if it does, "Dependencies installed" is displayed regardless.

**Comment by MoustaphaDev** [comment]
I have an API design in mind. Put the `while` (`update` internally) function in a `try-catch`.
If the `while` function throws an error or is a rejected promise, display the message of the rejected promise/error as the error state

**Comment by skirianov** [comment]
https://github.com/withastro/astro/issues/8990 

As part of this Issue, `spinner` is updated to handle `onError` function. 

Closed here #25

**Comment by MoustaphaDev** [comment]
Thanks for making a PR @skirianov!
